### ISSUE TITLE
--- End of stack trace from previous location where exception was thrown ---

### ISSUE THREAD

**Issue by Scott-GMI** [1249993110/7DaysToDie-ServerKit#23]
Hi. I was tailing my server log file and saw the following error in the attached file. This happened as gameplay moved from night to day (4:00 AM in the game). I was in the server testing and saw the zombies despawn and then the following showed up in the log. Using version 10.42

[log.txt](https://github.com/user-attachments/files/17109844/log.txt)

Thank you, Scott

**Comment by 1249993110** [comment]
Thanks for your feedback. Have a nice rest of the day 🙂
