### ISSUE TITLE
Typo - Server Settings Description

### ISSUE THREAD

**Issue by Scott-GMI** [1249993110/7DaysToDie-ServerKit#26]
It's just a small typo.

Please see the attached screen capture.  It looks like you duplicated the description for an option in the config.

ZombieFeralMove  >>> Zombie BM Move. <<<   0-4 (Walk, Jog, Run, Sprint, Nightmare)

ZombieBMMove  >>>Zombie BM Move. <<<<    0-4 (Walk, Jog, Run, Sprint, Nightmare)

Thinking the description ZombieFeralMove should be Zombie Feral Move

Scott
![web](https://github.com/user-attachments/assets/0535b4c4-8346-4ca1-bab1-c146bc47e058)

**Comment by 1249993110** [comment]
Thank you for your feedback, this typo will be corrected in the next version, you can contribute translations [here](https://github.com/1249993110/7DaysToDie-ServerKit/blob/main/CONTRIBUTING.md#how-can-i-help-contribute-translated-content)
