### ISSUE TITLE
同一个服务器同一IP下不同端口使用问题

### ISSUE THREAD

**Issue by 451891358** [1249993110/7DaysToDie-ServerKit#32]
ERR [LSTY] Initialize mod: SdtdServerKit failed.
System.Exception: Startup Owin Host Server failed. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.Sockets.SocketException: 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。

同一个服务器同一个IP下使用不同端口开服出现此问题

前一个服  "WebUrl": "http://*:59988",
  "WebSocketPort": 59989,
  "WebSocketUrl": "ws://{hostname}:59989/ws",
 第二个服  "WebUrl": "http://*:60188",
  "WebSocketPort": 60189,
  "WebSocketUrl": "ws://{hostname}:60189/ws",

**Comment by 1249993110** [comment]
检查是否有其他程序占用

**Comment by 451891358** [comment]
已经检查了没有其他程序占用

**Comment by 1249993110** [comment]
此错误由系统内部抛出，结果明确为端口已被占用。如需远程协助可加入QQ群
